[package]
name = "rust_lib_turms_chat_demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
image = "0.25.5"
sysinfo = "0.33.0"
icu_collator = "1.5.0"
icu_locid = "1.5.0"