name: turms_chat_demo
publish_to: 'none'
version: 0.0.1

platforms:
  linux:
  macos:
  windows:
# TODO: Add support for the following platforms:
#  web:
#  android:
#  ios:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  # flutter.dev
  animations: ^2.0.11
  # dart.dev
  async: ^2.11.0
  # bbflight.com
  # Note: No web support
  background_downloader: ^8.5.6
  # dart.dev
  convert: ^3.1.1
  # flutter.dev
  cross_file: ^0.3.4+2
  # dart.dev
  crypto: ^3.0.5
  # fluttercommunity.dev
  device_info_plus: ^11.1.0
  # unverified uploader
  dotted_border: ^2.1.0
  # simonbinder.eu
  drift: ^2.22.0
  # miguelruivo.com
  file_picker: ^8.1.2
  # dart.dev
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  # fluttercandies
  flutter_image_compress: ^2.3.0
  # jasonrai.ca
  flutter_keyboard_visibility: ^6.0.0
  flutter_inappwebview: ^6.1.5
  # dexterx.dev
  flutter_local_notifications: ^18.0.0
  # Flutter
  flutter_localizations:
    sdk: flutter
  # dash-overflow.net
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: ^2.5.0
  flutter_secure_storage: ^9.2.2
  # dnfield.dev
  flutter_svg: ^2.0.10+1
  # midoridesign.studio
  gal: ^2.3.0
  # material.io
  google_fonts: ^6.2.1
  # dart.dev
  http: ^1.2.2
  # loki3d.com
  # Don't resize GIF images because the "image" package
  # is buggy for resizing GIF images.
  # e.g. https://github.com/brendan-duncan/image/issues/588
  # TODO: waiting for them to be fixed.
  image: ^4.2.0
  # flutter.dev
  image_picker: ^1.1.2
  intl: any
  # lamnhan.dev
  isolate_manager: ^5.6.1
  # tools.dart.dev
  json_rpc_2: ^3.0.2
  markdown: ^7.2.2
  # hiveright.tech
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/102560
  # We need this dependency to support icon weight.
  material_symbols_icons: ^4.2800.2
  # media-kit.dev
  media_kit: ^1.1.10+1
  media_kit_libs_audio: ^1.0.5
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
#  media_kit_libs_android_video: any
#  media_kit_libs_ios_video: any
#  media_kit_libs_linux: any
#  media_kit_libs_macos_video: any
#  media_kit_libs_windows_video: any
  # buildtoapp.com
  open_file: ^3.5.7
  # fluttercommunity.dev
  package_info_plus: ^8.0.2
  # dart.dev
  path: ^1.9.0
  # flutter.dev
  path_provider: ^2.1.4
  # google.dev
  protobuf: ^3.1.0
  # tools.dart.dev
  pub_semver: ^2.1.4
  responsive_framework: ^1.5.1
  # dash-overflow.net
  riverpod_annotation: ^2.3.5
  rust_lib_turms_chat_demo:
    path: rust_builder
  # tools.dart.dev
  shelf_web_socket: ^2.0.0
  # simonbinder.eu
  sqlite3_flutter_libs: ^0.5.24
  # nativeshell.dev
  super_clipboard: ^0.9.0-dev.3
  # nativeshell.dev
  # Note: The Flutter team recommends "super_drag_and_drop".
  super_drag_and_drop: ^0.9.0-dev.3
  # nativeshell.dev
  super_hot_key: ^0.9.0-dev.3
  # leanflutter.dev
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/81644
  tray_manager: ^0.3.0
  turms_client_dart:
    path: ../turms-client-dart/
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  # flutter.dev
  video_player: ^2.9.1
  # media-kit.dev
  video_player_media_kit: ^1.0.5
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^3.0.1
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/31373
  window_manager: ^0.4.2
  windows_notification: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.13
  # invertase.io
  custom_lint: ^0.7.0
  drift_dev: ^2.22.0
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_platform_alert: ^0.6.1
  flutter_test:
    sdk: flutter
  #  matcher: ^0.12.16
  #  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  riverpod_lint: ^2.3.13

flutter:
  # Ensures that the Material Icons font is included with our application
  uses-material-design: true
  # Used to generate l10n files
  generate: true
  assets:
#    - assets/fonts/
    - assets/images/
flutter_gen:
  output: lib/infra/assets/